name: Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Replace with the Python version you need
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run build script
        run: python -m scripts.build
      - name: Deploy to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git branch -D deployment || true
          git checkout -b deployment
          cp -r site /tmp/
          rm -rf *
          rm -rf .github .gitignore
          cp -r /tmp/site/* ./
          git add -A
          git commit -m "build site."
          git push origin deployment --force
